# Generated by Django 3.2.12 on 2022-04-21 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiant_db', '0002_alter_etudiant_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='cin',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='contact',
            field=models.CharField(max_length=10),
        ),
    ]
